from decimal import Decimal

from sqlalchemy.orm import Session

from src.app.modules.products.model import Product


def seed_products(db: Session) -> None:
    products_data = [
        {
            "product_id": 1,
            "product_name": "Xiaozhubangchu keycaps Mario bàn phím cơ 124 phím keycaps chất lượng cao kết hợp",
            "price": Decimal("301000.00"),
            "sale_price": Decimal("219730.00"),
            "quantity": 73,
            "rating": Decimal("4.30"),
            "sold": 456,
            "brand": "XiaoZhu",
            "origin": "Trung Quốc",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1754451108/dc276163-41e7-48e7-8967-a34fe8eea7e7.png",
            "description": "Bộ keycap Xiaozhubangchu Mario 124 phím là một set keycap được thiết kế dành cho bàn phím cơ, lấy cảm hứng từ thế giới game Super Mario nổi tiếng, giúp bạn cá nhân hóa chiếc bàn phím của mình.Dưới đây là mô tả chi tiết sản phẩm dựa trên các thông số kỹ thuật phổ biến của set keycap này:Thông số Kỹ thuật ChínhThuộc tínhChi tiếtTác dụngChủ đềSuper Mario (Nhiều biến thể màu sắc: Đỏ, Vàng, Retro...)Mang lại phong cách trẻ trung, cổ điển và bắt mắt.Số lượng124 phím (hoặc xấp xỉ 119 - 125 nút)Đầy đủ để tương thích với hầu hết các layout bàn phím cơ phổ thông (60%, 61, 68, 84, 87, 98, 104, 108 phím).Chất liệuPBT (Polybutylene Terephthalate)Chất liệu cao cấp, có độ bền vượt trội, chống bám dầu tốt hơn ABS, và cho cảm giác gõ đầm tay, chắc chắn.Công nghệ InDye-sublimation (Dye-sub)Công nghệ in nhiệt, giúp mực thấm sâu vào nhựa, đảm bảo ký tự và hình ảnh không bị phai màu hay bị mờ trong suốt quá trình sử dụng lâu dài.ProfileThường là Cherry Profile hoặc SADA/OEM ProfileProfile Cherry/OEM là chuẩn phổ biến, có độ cao vừa phải, mang lại cảm giác gõ thoải mái, phù hợp với hầu hết người dùng.Đặc điểm Nổi bậtThiết kế Độc đáo: Các keycap được trang trí bằng các biểu tượng đặc trưng của game Mario như: nấm, ngôi sao, ống nước, các nhân vật (Mario, Luigi, Toad),... tạo nên một bộ keycap sinh động và mang tính sưu tập cao.Độ bền và Cảm giác Gõ: Nhờ chất liệu PBT dày dặn (thường là thick PBT) và công nghệ in Dye-sublimation, bộ keycap không chỉ bền bỉ mà còn mang lại âm thanh và cảm giác gõ tốt hơn, ấm và trầm hơn so với keycap ABS mỏng.Khả năng Tương thích: Với số lượng 124 phím, set keycap này thường đi kèm các phím bổ sung (Novelty keys) và các kích thước phím đặc biệt (như Shift 1.75u, Alt/Fn/Ctrl 1u, phím cách ngắn) để đảm bảo hỗ trợ cho nhiều loại layout khác nhau, bao gồm cả các bàn phím TKL, Fullsize và các layout Custom.Bộ keycap này là lựa chọn tuyệt vời cho những người hâm mộ Mario hoặc bất kỳ ai muốn nâng cấp bàn phím cơ của mình với một bộ keycap chất lượng cao, có tính thẩm mỹ và độ bền lâu dài.",
            "category_id": 18,
        },
        {
            "product_id": 2,
            "product_name": "Xiaozhubangchu Pikachu keycap MOA chiều cao PBT keycap năm mặt thăng hoa dễ thương tùy chỉnh bộ keycap cá tính",
            "price": Decimal("267000.00"),
            "sale_price": Decimal("186900.00"),
            "quantity": 417,
            "rating": Decimal("4.80"),
            "sold": 266,
            "brand": "XiaoZhu",
            "origin": "Trung Quốc",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1754451144/d6a01a78-6626-498b-a1ed-1174c8de0ab1.png",
            "description": "Xiaozhubangchu Pikachu keycap MOA chiều cao PBT keycap năm mặt thăng hoa dễ thương tùy",
            "category_id": 18,
        },
        {
            "product_id": 3,
            "product_name": "[Nhập ELHP15 giảm 15% tối đa 3TR] Laptop HP 15s-fq2712TU (7C0X2PA)/Intel Core i3-1115G4 / RAM 8GB/ 256GB",
            "price": Decimal("13590000.00"),
            "sale_price": Decimal("10192500.00"),
            "quantity": 729,
            "rating": Decimal("4.00"),
            "sold": 661,
            "brand": "HP",
            "origin": "Việt Nam",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1754451166/e7ea0020-9be1-424e-9915-7f70cc688192.png",
            "description": None,
            "category_id": 2,
        },
        {
            "product_id": 4,
            "product_name": "Điện thoại Apple IPhone 14 128GB",
            "price": Decimal("26900000.00"),
            "sale_price": Decimal("19368000.00"),
            "quantity": 1205,
            "rating": Decimal("4.90"),
            "sold": 7896,
            "brand": "Apple",
            "origin": "USA",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1754451186/89e51f43-2cb8-459d-ae7e-053875606e49.png",
            "description": "iPhone 14 128GB được xem là mẫu smartphone bùng nổ của nhà táo trong năm 2022, ấn tượng với ngoại hình trẻ trung, màn hình chất lượng đi kèm với những cải tiến về hệ điều hành và thuật toán xử lý hình ảnh, giúp máy trở thành cái tên thu hút được đông đảo người dùng quan tâm tại thời điểm ra mắt.\niPhone 14 sở hữu thiết kế cao cấp\nVới phiên bản tiêu chuẩn thì nhà Apple vẫn giữ nguyên kiểu dáng thiết kế so với thế hệ tiền nhiệm, vẫn là mặt lưng phẳng cùng bộ khung vuông giúp máy trở nên hiện đại hơn.\n\nThiết kế hiện đại - iPhone 14 128GBiPhone 14 128GB được xem là mẫu smartphone bùng nổ của nhà táo trong năm 2022, ấn tượng với ngoại hình trẻ trung, màn hình chất lượng đi kèm với những cải tiến về hệ điều hành và thuật toán xử lý hình ảnh, giúp máy trở thành cái tên thu hút được đông đảo người dùng quan tâm tại thời điểm ra mắt.\niPhone 14 sở hữu thiết kế cao cấp\nVới phiên bản tiêu chuẩn thì nhà Apple vẫn giữ nguyên kiểu dáng thiết kế so với thế hệ tiền nhiệm, vẫn là mặt lưng phẳng cùng bộ khung vuông giúp máy trở nên hiện đại hơn.\n\nThiết kế hiện đại - iPhone 14 128GB\n\niPhone 14 có kích thước chiều ngang là 71.5 mm nên máy có thể dễ dàng nằm gọn trong lòng bàn tay mỗi khi sử dụng, điều này làm cho điện thoại trở nên phù hợp hơn với nhiều đối tượng người dùng hơn, kể cả những bạn nữ có bàn tay nhỏ nhắn.\n\nCamera - iPhone 14 128GB\n\nMặt lưng của điện thoại được thiết kế từ kính cường lực và hoàn thiện theo kiểu nhẵn bóng, theo mình thì cách làm này giúp cho iPhone 14 trông cuốn hút hơn, bên cạnh đó máy cũng khá bền bỉ có thể mang lại khả năng chống chịu các vết xước được tốt hơn.\n\nMặt lưng kính cường lực - iPhone 14 128GB\n\nCó một lưu ý nhỏ ở phần thiết kế là máy khá dễ bám dấu vân tay, điều này càng thêm lộ rõ ở những phiên bản có màu đậm như đen và đỏ, còn ở các phiên bản màu sáng như xanh dương, trắng và tím nhạt thì điều này cũng được cải thiện.\n\nHạn chế vết bám - iPhone 14 128GB\n\nTuy nhiên đây cũng là điều thường gặp trên các mẫu điện thoại có mặt lưng kính nên mình cũng không xem đây là điểm trừ dành cho iPhone 14, bằng cách trang bị thêm ốp lưng là ta đã có thể khắc phục hoàn toàn tình trạng trên và còn tăng thêm độ bền cho điện thoại.\n\nNăm nay Apple cho ra mắt hai phiên bản có màu mới dành cho iPhone 14 là tím nhạt và xanh dương, theo mình thấy thì màu xanh này có màu dịu nhẹ hơn so với iPhone 13. Vậy nên nhờ màu sắc mà mình có thể dễ dàng phân biệt giữa hai dòng điện thoại, nếu muốn mọi người xung quanh biết được rằng bạn đang sở hữu iPhone 14 thì hai màu sắc này sẽ là sự lựa chọn rất phù hợp.\n\nTrong khi iPhone 14 128GB vẫn là một lựa chọn phổ biến với ngoại hình trẻ trung và hiệu năng ổn định, thì iPhone 16 128GB đã ra mắt mang đến những cải tiến vượt trội. Nếu bạn đang tìm kiếm những tính năng mới nhất và công nghệ tiên tiến nhất, iPhone 16 128GB có thể là một lựa chọn tốt hơn, đem lại trải nghiệm người dùng cao cấp và hiện đại hơn.\n\niPhone 14 có kích thước chiều ngang là 71.5 mm nên máy có thể dễ dàng nằm gọn trong lòng bàn tay mỗi khi sử dụng, điều này làm cho điện thoại trở nên phù hợp hơn với nhiều đối tượng người dùng hơn, kể cả những bạn nữ có bàn tay nhỏ nhắn.\n\nCamera - iPhone 14 128GB\n\nMặt lưng của điện thoại được thiết kế từ kính cường lực và hoàn thiện theo kiểu nhẵn bóng, theo mình thì cách làm này giúp cho iPhone 14 trông cuốn hút hơn, bên cạnh đó máy cũng khá bền bỉ có thể mang lại khả năng chống chịu các vết xước được tốt hơn.\n\nMặt lưng kính cường lực - iPhone 14 128GB\n\nCó một lưu ý nhỏ ở phần thiết kế là máy khá dễ bám dấu vân tay, điều này càng thêm lộ rõ ở những phiên bản có màu đậm như đen và đỏ, còn ở các phiên bản màu sáng như xanh dương, trắng và tím nhạt thì điều này cũng được cải thiện.\n\nHạn chế vết bám - iPhone 14 128GB\n\nTuy nhiên đây cũng là điều thường gặp trên các mẫu điện thoại có mặt lưng kính nên mình cũng không xem đây là điểm trừ dành cho iPhone 14, bằng cách trang bị thêm ốp lưng là ta đã có thể khắc phục hoàn toàn tình trạng trên và còn tăng thêm độ bền cho điện thoại.\n\nNăm nay Apple cho ra mắt hai phiên bản có màu mới dành cho iPhone 14 là tím nhạt và xanh dương, theo mình thấy thì màu xanh này có màu dịu nhẹ hơn so với iPhone 13. Vậy nên nhờ màu sắc mà mình có thể dễ dàng phân biệt giữa hai dòng điện thoại, nếu muốn mọi người xung quanh biết được rằng bạn đang sở hữu iPhone 14 thì hai màu sắc này sẽ là sự lựa chọn rất phù hợp.\n\nTrong khi iPhone 14 128GB vẫn là một lựa chọn phổ biến với ngoại hình trẻ trung và hiệu năng ổn định, thì iPhone 16 128GB đã ra mắt mang đến những cải tiến vượt trội. Nếu bạn đang tìm kiếm những tính năng mới nhất và công nghệ tiên tiến nhất, iPhone 16 128GB có thể là một lựa chọn tốt hơn, đem lại trải nghiệm người dùng cao cấp và hiện đại hơn.",
            "category_id": 1,
        },
        {
            "product_id": 5,
            "product_name": "Siêu nhân khùng",
            "price": Decimal("9999.00"),
            "sale_price": Decimal("9999.00"),
            "quantity": 0,
            "rating": Decimal("0.00"),
            "sold": 321,
            "brand": "Hoang",
            "origin": "Hàn Cuốc",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1754491334/gundam-anime-2k-wallpaper-uhdpaper.com-724_3_a_hrzn2g.jpg",
            "description": "khùng nhất",
            "category_id": 1,
        },
        {
            "product_id": 6,
            "product_name": "Màn hình Samsung 27 inch Cong LC27R500FHEXXV FHD AMD FreeSync 4ms Bảo vệ mắt Khử nhấp nháy",
            "price": Decimal("4120000.00"),
            "sale_price": Decimal("4120000.00"),
            "quantity": 138,
            "rating": Decimal("0.00"),
            "sold": 783,
            "brand": "Samsung",
            "origin": "Việt Nam",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1754643786/vn-11134201-7r98o-lwcdqa92w3lb3a_d248ur.jpg",
            "description": "Màn hình Samsung 27″ cong FHD (1 920×1 080), tấm nền VA, độ cong 1800R — mang lại cảm giác xem đắm chìm hơn so với màn phẳng \nThiết kế bezel‑less 3 cạnh, chân đế Y‑shape, dáng mỏng nhẹ, tạo điểm nhấn hiện đại cho góc học, làm việc hay gaming \nĐộ tương phản cao ~3 000:1, góc nhìn tốt, màu sắc rõ ràng, đen sâu — phù hợp xem phim, chơi game, đồ họa nhẹ \nThời gian phản hồi 4 ms (GtG), tần số 60 Hz, hỗ trợ AMD FreeSync giúp giảm xé hình khi chơi game nhẹ hoặc xem video trơn tru \nKết nối HDMI + HDMI (2 cổng), không có DisplayPort — cần lưu ý khi kết nối PC chuyên dụng \nNgười dùng đánh giá chất lượng hiển thị “rực rỡ, đáng đồng tiền”, thiết lập dễ dàng, phù hợp desktop/laptop \nMột số phản hồi tiêu cực: không có IPS, 60 Hz, đã nhận một số mẫu lỗi — người mua nên kiểm tra kỹ trước khi lắp \nThiết kế cong giúp mắt dễ chịu hơn khi xem lâu dài; nên dùng với bàn rộng để tận dụng không gian hiệu quả. \nPhù hợp học tập, văn phòng, chơi game nhẹ, xem phim; giá mềm (3.4 triệu) là lựa chọn tốt trong tầm phổ thông.",
            "category_id": 1,
        },
        {
            "product_id": 8,
            "product_name": "Điện thoại Apple IPhone 14 128GB",
            "price": Decimal("27900000.00"),
            "sale_price": Decimal("27900000.00"),
            "quantity": 124,
            "rating": Decimal("0.00"),
            "sold": 675,
            "brand": "Apple",
            "origin": "USA",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1754709456/sg-11134201-23020-q78nka801cnv83_bbu8jd.jpg",
            "description": "iPhone 14 (2022) sở hữu màn hình 6.1″ Super Retina XDR OLED, độ phân giải 2532×1170, độ sáng 800 nit (typical), 1200 nit (HDR), độ tương phản 2 000 000:1 — hình ảnh sắc nét sống động \nChip A15 Bionic (5 nm, 6‑core CPU, 5‑core GPU, 16‑core Neural Engine), RAM 6 GB giúp hiệu năng vượt trội trong các tác vụ, dù không phải chip mới nhất \nBộ nhớ 128 GB đáp ứng lưu trữ ảnh, video, app; hỗ trợ thêm các tùy chọn 256/512 GB \nHệ thống camera kép: 12 MP Wide + 12 MP Ultrawide, hỗ trợ Cinematic Mode, Action Mode, quay 4K 60fps — chụp video mượt, chống rung mạnh mẽ \nPin 3 279 mAh, thời lượng xem video 20h, stream 16h, nghe nhạc đến 80h — cải thiện nhẹ so với iPhone 13 \nTiêu chuẩn IP68 chống nước/bụi, tích hợp tính năng SOS qua vệ tinh (từ Nov 2022, miễn phí 2 năm) \nKết nối luôn được cập nhật với Wi‑Fi 6, Bluetooth 5.x, Lightning; màu sắc đa dạng như Blue, Midnight, Starlight, Purple, Yellow, Product Red \nThiết kế vỏ nhôm, kính Ceramic Shield — nhẹ nhưng chắc, khả năng chống va đập khá tốt. \nHỗ trợ iOS 16 trở lên, cập nhật bảo mật dài hạn; phù hợp người dùng muốn trải nghiệm ổn định, lâu dài.",
            "category_id": 1,
        },
        {
            "product_id": 9,
            "product_name": "Sạc dự phòng Xmobile 20W Y73",
            "price": Decimal("800000.00"),
            "sale_price": Decimal("800000.00"),
            "quantity": 329,
            "rating": Decimal("0.00"),
            "sold": 456,
            "brand": "Xmobile",
            "origin": "Trung Quốc",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1760012556/pin-sac-du-phong-10000mah-type-c-pd-qc3-0-20w-xmobile-y73-thumb-600x600_1_zicbiw.jpg",
            "description": "Dung lượng pin: 10000 mAh\nHiệu suất sạc: 68%\nLõi pin: Li-Ion\nCông nghệ / Tiện ích: Màn hình LED báo hiệu, Power Delivery, Quick Charge 3.0\nThời gian sạc đầy pin: 3 giờ 30 phút (dùng Adapter 3A)\n",
            "category_id": 71,
        },
        {
            "product_id": 10,
            "product_name": "Đồng hồ ELIO Nàng Thơ 28 mm Nữ ES034-01",
            "price": Decimal("490000.00"),
            "sale_price": Decimal("490000.00"),
            "quantity": 1232,
            "rating": Decimal("0.00"),
            "sold": 1,
            "brand": "Elio",
            "origin": "Việt Nam",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1760013213/elio-es034-01-nu-2-750x500_1_p0kxfe.jpg",
            "description": "- Thuộc bộ sưu tập Nàng thơ ra mắt đầu năm 2021 của hãng đồng hồ Elio - thương hiệu đồng hồ uy tín của Việt Nam, được kinh doanh độc quyền tại Thế Giới Di Động\n\n- Đồng hồ có đường kính mặt 28 mm, độ rộng dây 12 mm\n\n- Đồng hồ ELIO Nàng Thơ 28 mm Nữ ES034-01 có dây và khung viền được gia công bằng hợp kim chịu lực tốt, cho cảm giác mát tay khi mang\n\n- Chỉ số chống nước 3 ATM: Bạn thoải mái đeo mẫu đồng hồ nữ này khi đi mưa, rửa tay, không mang khi tắm, bơi, lặn",
            "category_id": 43,
        },
        {
            "product_id": 11,
            "product_name": "Máy tính xách tay Apple xịn",
            "price": Decimal("32900000.00"),
            "sale_price": Decimal("32900000.00"),
            "quantity": 2345,
            "rating": Decimal("0.00"),
            "sold": 444,
            "brand": "Apple",
            "origin": "USA",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1760013404/1cba156175a5ef0b0d356b52451b4c42_1_eji9xo.jpg",
            "description": "MacBook Air 2022 M2 sở hữu chip Apple M2 8‑core CPU/10‑core GPU, cho hiệu năng mạnh mẽ gấp đôi M1 trong nhiều tác vụ đa nhiệm và xử lý đồ họa nhẹ. \nRAM gốc 8 GB (LPDDR5), SSD 256 GB – đủ dùng cho học lập trình, đồ họa nhẹ, chỉnh video 1080p. \nMàn hình Liquid Retina 13.6″ 2560×1664, 500 nit, hỗ trợ P3 wide colour, True Tone. \nThiết kế nguyên khối mỏng nhẹ (1.24 kg), thân nhôm tái chế, bền và thân thiện môi trường. \nTouch ID, camera FaceTime HD 1080p, macOS đột phá về bảo mật và hệ sinh thái. \nThời lượng pin đến 18 giờ xem video, 15 giờ duyệt web – dẫn đầu phân khúc laptop mỏng nhẹ. \n2 cổng USB-C/Thunderbolt 4, jack tai nghe 3.5 mm, hỗ trợ sạc MagSafe 3. \nTheo The Verge, MacBook Air M2 là “một chiếc MacBook toàn diện với hiệu năng, thiết kế và pin xuất sắc”. \nPhù hợp sinh viên, người sáng tạo nội dung, lập trình viên, nhân viên văn phòng chuyên nghiệp.",
            "category_id": 2,
        },
        {
            "product_id": 34,
            "product_name": "Chuột Gaming không dây Rapoo VT960S Wireless 2.4G pin sạc",
            "price": Decimal("170000.00"),
            "sale_price": Decimal("149000.00"),
            "quantity": 1231,
            "rating": Decimal("5.00"),
            "sold": 123,
            "brand": "Rapoo",
            "origin": "Trung Quốc",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1764000259/vn-11134207-7qukw-lfakrxoi6b9m8d_uklxfg.jpg",
            "description": None,
            "category_id": 2,
        },
        {
            "product_id": 35,
            "product_name": "Apple iPad (Gen 9) WIFI Chính hãng (ZA/A)",
            "price": Decimal("12900000.00"),
            "sale_price": Decimal("12900000.00"),
            "quantity": 12,
            "rating": Decimal("5.00"),
            "sold": 56,
            "brand": "Apple",
            "origin": "USA",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1764000363/ada38c6e6ea23c99065eba067b184b0f_nyqm6w.jpg",
            "description": "iPad 9 (Gen 2021) sở hữu màn 10.2″ Retina, độ phân giải 2160×1620, True Tone, hỗ trợ Apple Pencil (1st Gen) – phù hợp học tập, vẽ, note nhẹ. \nTrang bị chip A13 Bionic, RAM 3 GB – đủ mạnh để chạy iPadOS 17 đa nhiệm, game nhẹ và trình duyệt nhanh. \nBộ nhớ 64 GB (có thêm lựa chọn 256 GB), thoải mái lưu tài liệu, video, ảnh. \nLoa stereo nằm ngang cho âm thanh tốt khi xem phim/xem video. \nCamera trước 12 MP Ultra Wide (sử dụng Center Stage tự động theo dõi), sau 8 MP chụp ổn cho Zoom, FaceTime, selfie. \nPin 32.4 Wh cho thời gian dùng thực tế đến 10 tiếng học/việc online. \nThiết kế thân nhôm, bền bỉ, kích thước gọn nhẹ (~487 g), cầm lâu không mỏi. \niPadOS hỗ trợ chia đôi màn hình, Slide Over, Apple Pencil và Smart Keyboard. \nHỗ trợ cập nhật phần mềm lâu dài (ít nhất 5–6 năm). \nPhù hợp học sinh, sinh viên, người dùng văn phòng và giải trí cơ bản.",
            "category_id": 2,
        },
        {
            "product_id": 36,
            "product_name": "Tai nghe Apple AirPods 3rd gen lightning charge",
            "price": Decimal("5310000.00"),
            "sale_price": Decimal("4590000.00"),
            "quantity": 543,
            "rating": Decimal("5.00"),
            "sold": 45645,
            "brand": "Apple",
            "origin": "USA",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1764000486/f2f9ddaf332def792d62021325ca0198_a7aztx.jpg",
            "description": "AirPods 3 (thế hệ 3) trang bị driver âm thanh mới, chất lượng cao hơn AirPods 2, bass sâu hơn, trung cao và treble rõ – phù hợp nghe nhạc và xem phim. \nThiết kế in-ear dạng open, không có đệm silicon, thoáng, nhẹ, cảm giác đeo dễ chịu, ít bí trong thời gian dài. \nHộp sạc hỗ trợ sạc Lightning hoặc tùy chọn sạc MagSafe, nâng tổng thời gian nghe lên ~30 giờ. \nTrang bị chip H1, kết nối nhanh qua iOS, macOS; hỗ trợ Spatial Audio với Dolby Atmos và Adaptive EQ. \nKháng nước đạt IPX4, phù hợp dùng khi tập thể thao nhẹ, chống mồ hôi, nhỏ giọt nước. \nMicro chất lượng cao, lọc gió tốt, phục vụ đàm thoại rõ ràng trong môi trường ngoài. \nTự động chuyển đổi giữa các thiết bị Apple, điều khiển bằng cảm ứng, hỗ trợ Siri rảnh tay. \nTheo review TechRadar/The Verge, AirPods 3 là nâng cấp đáng kể so với Gen 2, nhất là về pin và Spatial Audio. \nPhù hợp người dùng iPhone, iPad, Mac muốn nâng cao trải nghiệm nghe nhạc, xem phim, học online. \nGiá khoảng 4.6 triệu, bảo hành Apple toàn cầu 12 tháng.",
            "category_id": 2,
        },
        {
            "product_id": 48,
            "product_name": "Thăng quan tiến chức",
            "price": Decimal("56366.00"),
            "sale_price": Decimal("1.55"),
            "quantity": 1,
            "rating": Decimal("0.00"),
            "sold": 0,
            "brand": "",
            "origin": "",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766319352/800-800_7822d16f-0a44-4403-ab66-ae68dc0e0bbb_ba0koh.webp",
            "description": "",
            "category_id": 1,
        },
        {
            "product_id": 49,
            "product_name": "Sách Thăng quan tiến chức ",
            "price": Decimal("1111111.00"),
            "sale_price": Decimal("123400.00"),
            "quantity": 1,
            "rating": Decimal("0.00"),
            "sold": 0,
            "brand": "1",
            "origin": "USA",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766324193/800-800_7822d16f-0a44-4403-ab66-ae68dc0e0bbb_felil9.webp",
            "description": "Cuốn sách cung cấp cho bạn đọc không chỉ là những lời khuyên bổ ích để giúp cho con đường quan lộ của mình rộng mở, mà nó còn là những chiến lược cụ thể, nhưng chú ý cốt tử trong con đường tiến chức của bạn. Bạn nghĩ, thăng quan tiến chức đơn giản chỉ là cố gắng làm việc ngày đêm, đem lại cho công ty những giá trị gia tăng lớn nhất có thể. Hay bạn nghĩ, thăng quan tiến chức là phải nịnh bợ sếp, tạo ấn tượng tốt với đồng nghiệp… Nếu bạn suy nghĩ như vậy, hoặc đã thực hiện những bước như vậy trong kế hoạch thăng tiến của mình thì bạn đã chọn sai con đường rồi. Cuốn sách này sẽ chỉ ra cho bạn thấy rằng, để thăng quan tiến chức bạn cần phải biết kết hợp nhuần nhuyễn giữa làm việc hiệu quả và xây dựng hình ảnh của bản thân mình. Thêm vào đó là bạn luôn luôn phải học hỏi để nâng cao trình độ của bản thân.\n\nTuy nhiên, đây cũng chỉ là bước cơ bản nhất trong con đường thăng tiến của bạn. Ngay cả khi bạn đã kết hợp đầy đủ cả hai yếu tố làm việc hiệu quả và xây dựng hình ảnh, ngay cả khi bạn luôn luôn cố gắng bồi đắp kiến thức cho bản thân thì cũng không có gì đảm bảo bạn sẽ thăng tiến, hay chí ít là lọt vào mắt xanh của sếp. Điều bạn còn thiếu ở đây chính là một kế hoạch, một kế hoạch cụ thể từng bước để tiến lên, bạn phải luôn hiểu rằng công việc nào cũng là buôn bán, và điều cốt yếu là trong mọi lúc mọi nơi mọi trường hợp thì điều đầu tiên bạn phải nghĩ đến là làm đẹp mặt sếp. Và còn vô số những kế hoạch, những thủ thuật, hay hơn thế là mưu mẹo để có thể thực sự thăng tiến đều có trong cuốn sách đầy hữu ích này.",
            "category_id": 70,
        },
        {
            "product_id": 50,
            "product_name": "Điện thoại OPPO Reno14 F 5G 12GB/256GB",
            "price": Decimal("11290000.00"),
            "sale_price": Decimal("11090000.00"),
            "quantity": 1437,
            "rating": Decimal("4.90"),
            "sold": 0,
            "brand": "Oppo",
            "origin": "Trung Quốc",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766906656/oppo-reno14-f-5g-blue-thumb-600x600_j8vaok.jpg",
            "description": 'OPPO Reno 14 F (12GB | 256GB) – Chuyên Gia Chân Dung AI Thế Hệ Mới\nOPPO Reno 14 F tái định nghĩa trải nghiệm smartphone tầm trung với thiết kế mỏng nhẹ đặc trưng, hiệu năng mạnh mẽ vượt bậc và hệ thống camera được nâng cấp toàn diện bởi trí tuệ nhân tạo (AI).\n\n💎 Thiết Kế Sang Trọng & Màn Hình Đỉnh Cao\nMỏng nhẹ tinh tế: Thân máy được hoàn thiện với độ mỏng ấn tượng, kết hợp cùng mặt lưng hiệu ứng dòng chảy Reno Glow chống bám vân tay hiệu quả.\n\nTầm nhìn vô cực: Màn hình AMOLED 6.7 inch độ phân giải Full HD+, hỗ trợ tần số quét 120Hz cho mọi thao tác vuốt chạm và chuyển động hình ảnh trở nên siêu mượt mà.\n\n🚀 Hiệu Năng Đột Phá - Lưu Trữ Thả Ga\nĐa nhiệm không giới hạn: Trang bị dung lượng RAM 12GB cực lớn, tích hợp công nghệ mở rộng RAM ảo giúp máy vận hành trơn tru ngay cả khi mở hàng chục ứng dụng cùng lúc.\n\nKhông gian lưu trữ rộng lớn: Bộ nhớ trong 256GB cho phép bạn thoải mái lưu trữ hàng ngàn video 4K và hàng chục nghìn bức ảnh chất lượng cao.\n\n📸 Hệ Thống Camera AI "Chuyên Gia Chân Dung"\nCamera chính 64MP: Độ phân giải cao mang lại chi tiết sắc nét ngay cả trong điều kiện thiếu sáng.\n\nThuật toán AI Portrait: Tự động tối ưu hóa tông màu da, xử lý xóa phông tự nhiên như máy ảnh chuyên nghiệp.\n\nSelfie 32MP: Tự tin trong mọi khung hình với camera trước tích hợp chế độ làm đẹp thông minh.\n\n🔋 Pin Bền Bỉ & Sạc Nhanh SuperVOOC\nNăng lượng cả ngày dài: Viên pin lớn 5000mAh đảm bảo nhu cầu giải trí và làm việc liên tục.\n\nSạc nhanh an toàn: Công nghệ sạc nhanh độc quyền của OPPO giúp nạp đầy năng lượng nhanh chóng mà vẫn đảm bảo tuổi thọ cho pin.\n📊 Bảng Thông Số Kỹ Thuật\nTính năng,Chi tiết\nMàn hình,"6.7"" AMOLED, Full HD+, 120Hz"\nRAM,12GB\nBộ nhớ trong,256GB\nCamera Sau,64MP (Chính) + 8MP (Góc rộng) + 2MP (Macro)\nCamera Trước,32MP\nPin,5000 mAh\nCông nghệ sạc,SuperVOOC',
            "category_id": 1,
        },
        {
            "product_id": 51,
            "product_name": "iPad Pro 13 inch (M4) WiFi 256GB",
            "price": Decimal("37990000.00"),
            "sale_price": Decimal("36490000.00"),
            "quantity": 500,
            "rating": Decimal("5.00"),
            "sold": 0,
            "brand": "Apple",
            "origin": "Mỹ",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766907032/ipad-pro-13-inch-m4-wifi-black-thumb-600x600_yfqv8w.jpg",
            "description": "🚀 iPad Pro M4 - Quyền năng siêu mỏng\r\n Mẫu máy tính bảng mỏng nhất từ trước đến nay của Apple với sức mạnh hủy diệt từ chip M4 thế hệ mới.\r\n\r\n 📺 Màn hình Ultra Retina XDR\r\n Công nghệ OLED hai lớp đột phá mang lại độ sáng cực cao và độ tương phản tuyệt đối cho trải nghiệm thị giác chưa từng có.\r\n\r\n ⚡ Chip M4 thần tốc\r\n Cấu trúc CPU và GPU mới giúp xử lý các tác vụ đồ họa 3D và AI nhanh gấp nhiều lần so với thế hệ tiền nhiệm.\r\n\r\n 📊 Thông số kỹ thuật\r\n Tính năng,Chi tiết\r\n Màn hình,13 inch Ultra Retina XDR OLED\r\n CPU,Apple M4 (9 lõi/10 lõi)\r\n RAM,8GB\r\n Bộ nhớ,256GB\r\n Kết nối,Wi-Fi 6E, Bluetooth 5.3",
            "category_id": 1,
        },
        {
            "product_id": 52,
            "product_name": "Điện thoại iPhone 16 Pro Max 256GB",
            "price": Decimal("34990000.00"),
            "sale_price": Decimal("33590000.00"),
            "quantity": 850,
            "rating": Decimal("4.90"),
            "sold": 0,
            "brand": "Apple",
            "origin": "Mỹ",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766917499/iphone-16-pro-max-sa-mac-thumb-1-600x600_yst4pb_1_cwv25w.jpg",
            "description": "📸 iPhone 16 Pro Max - Đỉnh cao công nghệ Titanium\n Sự kết hợp hoàn hảo giữa vật liệu Titanium bền bỉ và nút điều khiển Camera Control hoàn toàn mới.\n\n 💎 Chip A18 Pro mạnh mẽ\n Được thiết kế cho trí tuệ Apple (Apple Intelligence), mang lại hiệu năng xử lý tác vụ thông minh vượt trội.\n\n 🎥 Hệ thống camera chuyên nghiệp\n Camera Fusion 48MP cho phép quay video 4K120 fps chuẩn điện ảnh, bắt trọn mọi khoảnh khắc.\n\n 📊 Thông số kỹ thuật\n Tính năng,Chi tiết\n Màn hình,6.9 inch Super Retina XDR OLED\n CPU,Apple A18 Pro\n RAM,8GB\n Bộ nhớ,256GB\n Pin,Hỗ trợ sạc nhanh MagSafe 25W",
            "category_id": 1,
        },
        {
            "product_id": 53,
            "product_name": "Loa Bluetooth JBL PartyBox Encore kèm 2 Micro",
            "price": Decimal("12900000.00"),
            "sale_price": Decimal("10500000.00"),
            "quantity": 199,
            "rating": Decimal("4.80"),
            "sold": 0,
            "brand": "JBL",
            "origin": "Mỹ",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766907084/loa-bluetooth-jbl-partybox-encore-2mic-thumb-5-600x600_y7kxft.jpg",
            "description": "🎵 JBL PartyBox Encore - Bùng nổ âm nhạc mọi nơi\r\n Chiếc loa kéo nhỏ gọn nhưng sở hữu chất âm JBL Original Pro cực kỳ uy lực, phù hợp cho mọi buổi tiệc.\r\n\r\n 🎤 Đi kèm 2 Micro không dây\r\n Tận hưởng những giây phút giải trí Karaoke đỉnh cao với hệ thống micro bắt âm nhạy và chống hú tốt.\r\n\r\n 🌈 Hiệu ứng đèn LED rực rỡ\r\n Đèn led đồng bộ theo nhịp nhạc tạo nên không gian giải trí sôi động và bắt mắt.\r\n\r\n 📊 Thông số kỹ thuật\r\n Tính năng,Chi tiết\r\n Công suất,100W RMS\r\n Thời lượng pin,Lên đến 10 giờ\r\n Chống nước,IPX4\r\n Kết nối,Bluetooth 5.1, USB, AUX\r\n Trọng lượng,6.3 kg",
            "category_id": 71,
        },
        {
            "product_id": 57,
            "product_name": "Laptop Lenovo LOQ 15IRX9 i5 13450HX/16GB/512GB/RTX3050",
            "price": Decimal("22990000.00"),
            "sale_price": Decimal("20490000.00"),
            "quantity": 150,
            "rating": Decimal("4.80"),
            "sold": 0,
            "brand": "Lenovo",
            "origin": "Trung Quốc",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766907347/lenovo-loq-15irx9-i5-83dv003cvn-638828191874856424-600x600_zfad3b.jpg",
            "description": '🔥 **Lenovo LOQ 15IRX9 - Chiến thần gaming thế hệ mới**\r\n Dòng laptop gaming quốc dân mới từ Lenovo, thừa hưởng hệ thống tản nhiệt tối tân từ dòng Legion cao cấp.\r\n\r\n 💻 **Hiệu năng xử lý cực đỉnh**\r\n Trang bị chip dòng HX siêu mạnh mẽ kết hợp cùng card đồ họa RTX 3050, cân mượt các tựa game Esport và đồ họa bán chuyên.\r\n\r\n ❄️ **Hệ thống tản nhiệt Hyperchamber**\r\n Thiết kế luồng khí thông minh giúp máy luôn mát mẻ và duy trì hiệu năng ổn định trong thời gian dài.\r\n\r\n 📊 **Thông số kỹ thuật**\r\n Tính năng,Chi tiết\r\n CPU,Intel Core i5 13450HX\r\n RAM,16GB DDR5\r\n Ổ cứng,512GB SSD NVMe\r\n VGA,NVIDIA GeForce RTX 3050 6GB\r\n Màn hình,"15.6"" FHD, 144Hz, G-Sync"',
            "category_id": 2,
        },
        {
            "product_id": 58,
            "product_name": "Laptop Acer Nitro V 15 ANV15-41-R2UP R5 7535HS/16GB/512GB/RTX2050",
            "price": Decimal("20490000.00"),
            "sale_price": Decimal("19990000.00"),
            "quantity": 119,
            "rating": Decimal("4.70"),
            "sold": 0,
            "brand": "Acer",
            "origin": "Đài Loan",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766907378/acer-nitro-v-15-anv15-41-r2up-r5-nhqpgsv004-638774737367845195-600x600_fncben.jpg",
            "description": '### **⚡ Acer Nitro V 15 - Định nghĩa lại laptop gaming tầm trung**\n\nSự lột xác về thiết kế với vẻ ngoài thanh lịch nhưng vẫn ẩn chứa sức mạnh đáng nể của dòng Nitro huyền thoại.\n\n**🎯 Trải nghiệm thị giác mượt mà**\nMàn hình tần số quét cao giúp loại bỏ hiện tượng xé hình, cho bạn lợi thế trong các trận combat nảy lửa.\n\n** 🔊 Âm thanh vòm DTS:X Ultra**\nHệ thống âm thanh sống động giúp bạn nghe rõ từng tiếng bước chân của đối thủ trong game.\n\n**📊 Thông số kỹ thuật**\n| Tính năng | Chi tiết |\n| :--- | :--- |\n| **CPU** | AMD Ryzen 5 7535HS |\n| **RAM** | 16GB DDR5 |\n| **Ổ cứng** | 512GB SSD NVMe |\n| **VGA** | NVIDIA GeForce RTX 2050 4GB |\n| **Màn hình** | 15.6" FHD, 144Hz, IPS |',
            "category_id": 2,
        },
        {
            "product_id": 59,
            "product_name": "Laptop HP 15-fc0085au R5 7520U/8GB/512GB/Bạc",
            "price": Decimal("14590000.00"),
            "sale_price": Decimal("12790000.00"),
            "quantity": 300,
            "rating": Decimal("4.60"),
            "sold": 0,
            "brand": "HP",
            "origin": "Mỹ",
            "image_src": "https://res.cloudinary.com/dojey70x3/image/upload/v1766907382/hp-15-fc0085au-r5-a6vv8pa-170225-110652-878-600x600_bdpfmi.jpg",
            "description": '### 💼 HP 15-fc0085au - Sự lựa chọn hoàn hảo cho dân văn phòng\n\nThiết kế tối giản, tinh tế với tông màu bạc sang trọng, đồng hành cùng bạn trong mọi cuộc họp và buổi học.\n\n#### 🚀 Hiệu năng ổn định từ Ryzen 5\nXử lý nhanh chóng các tác vụ văn phòng, duyệt web nhiều tab và chỉnh sửa ảnh cơ bản mượt mà.\n\n#### 🔋 Pin bền bỉ & Bàn phím gõ êm\nHành trình phím sâu cho cảm giác gõ thoải mái trong thời gian dài, cùng thời lượng pin đáp ứng tốt một ngày làm việc.\n\n#### 📊 Thông số kỹ thuật\n\n| Tính năng | Chi tiết |\n| :--- | :--- |\n| **CPU** | AMD Ryzen 5 7520U |\n| **RAM** | 8GB LPDDR5 |\n| **Ổ cứng** | 512GB SSD NVMe |\n| **VGA** | AMD Radeon Graphics |\n| **Màn hình** | 15.6" FHD, Chống chói |',
            "category_id": 2,
        },
    ]

    for item in products_data:
        # Sử dụng merge để kiểm tra theo khóa chính (product_id).
        # Nếu đã có -> Cập nhật; Nếu chưa có -> Thêm mới.
        db.merge(Product(**item))

    db.commit()
