"""refactor(shipping): update shipping address structure

Revision ID: 25e5292b1b53
Revises: 273026c850bc
Create Date: 2026-09-29 14:53:12.503854

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25e5292b1b53"
down_revision: str | Sequence[str] | None = "273026c850bc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # Xóa index và bảng cũ nếu đã tồn tại để tránh xung đột
    op.execute("DROP INDEX IF EXISTS ix_shipping_addresses_user_id;")
    op.execute("DROP TABLE IF EXISTS shipping_addresses CASCADE;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shipping_addresses",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Mã định danh địa chỉ",
        ),
        sa.Column(
            "phone",
            sa.String(length=20),
            nullable=False,
            comment="Số điện thoại người nhận",
        ),
        sa.Column(
            "recipient_name",
            sa.String(length=255),
            nullable=False,
            comment="Tên người nhận",
        ),
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="Mã người dùng sở hữu địa chỉ"
        ),
        sa.Column(
            "province_code",
            sa.String(length=20),
            nullable=False,
            comment="Mã tỉnh/thành phố",
        ),
        sa.Column(
            "ward_code", sa.String(length=20), nullable=False, comment="Mã phường/xã"
        ),
        sa.Column(
            "address_line",
            sa.String(length=255),
            nullable=False,
            comment="Số nhà, tên đường, căn hộ...",
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            comment="Địa chỉ được chọn mặc định khi checkout",
        ),
        sa.ForeignKeyConstraint(
            ["province_code"],
            ["provinces.code"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["ward_code"],
            ["wards.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shipping_addresses_user_id"),
        "shipping_addresses",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_shipping_addresses_user_id"), table_name="shipping_addresses"
    )
    op.drop_table("shipping_addresses")
    # ### end Alembic commands ###
