"""add index to ward province code

Revision ID: 273026c850bc
Revises: c78373278ca0
Create Date: 2026-09-29 14:46:31.862177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273026c850bc'
down_revision: Union[str, Sequence[str], None] = 'c78373278ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wards_province_code'), 'wards', ['province_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wards_province_code'), table_name='wards')
    # ### end Alembic commands ###
