"""migrate users to supabase auth

Revision ID: 2bf29a9be4ea
Revises: 6c7e0b8ba4b2
Create Date: 2026-09-24 15:07:15.128009

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2bf29a9be4ea"
down_revision: str | Sequence[str] | None = "6c7e0b8ba4b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_password_reset_token_token"), table_name="password_reset_token"
    )
    op.drop_table("password_reset_token")
    op.drop_index(op.f("ix_refresh_token_token"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.add_column(
        "users",
        sa.Column(
            "auth_user_id",
            sa.UUID(),
            nullable=True,
            comment="UUID người dùng từ Supabase Auth",
        ),
    )
    op.alter_column(
        "users",
        "user_id",
        existing_type=sa.UUID(),
        comment="UUID định danh duy nhất của người dùng trong application",
        existing_comment="UUID định danh duy nhất của người dùng",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        comment="Tên đăng nhập của người dùng",
        existing_comment="Tên đăng nhập duy nhất",
    )
    op.alter_column(
        "users",
        "provider",
        existing_type=sa.VARCHAR(length=255),
        comment="Nhà cung cấp xác thực",
        existing_comment="Nhà cung cấp đăng nhập (LOCAL, GOOGLE...)",
        existing_nullable=True,
    )
    op.create_unique_constraint("uq_users_auth_user_id", "users", ["auth_user_id"])
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Mật khẩu đã được mã hóa (băm)",
        ),
    )
    op.drop_constraint("uq_users_auth_user_id", "users", type_="unique")
    op.alter_column(
        "users",
        "provider",
        existing_type=sa.VARCHAR(length=255),
        comment="Nhà cung cấp đăng nhập (LOCAL, GOOGLE...)",
        existing_comment="Nhà cung cấp xác thực",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        comment="Tên đăng nhập duy nhất",
        existing_comment="Tên đăng nhập của người dùng",
    )
    op.alter_column(
        "users",
        "user_id",
        existing_type=sa.UUID(),
        comment="UUID định danh duy nhất của người dùng",
        existing_comment="UUID định danh duy nhất của người dùng trong application",
        existing_nullable=False,
    )
    op.drop_column("users", "auth_user_id")
    op.create_table(
        "refresh_token",
        sa.Column(
            "id",
            sa.BIGINT(),
            autoincrement=True,
            nullable=False,
            comment="Mã định danh token",
        ),
        sa.Column(
            "token",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Chuỗi Refresh Token duy nhất",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="Mã người dùng sở hữu token",
        ),
        sa.Column(
            "expiry_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="Thời điểm hết hạn của refresh token",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("refresh_token_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("refresh_token_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("refresh_token_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_refresh_token_token"), "refresh_token", ["token"], unique=True
    )
    op.create_table(
        "password_reset_token",
        sa.Column(
            "id",
            sa.INTEGER(),
            autoincrement=True,
            nullable=False,
            comment="Mã định danh bản ghi",
        ),
        sa.Column(
            "token",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Chuỗi token đặt lại mật khẩu",
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="Mã người dùng yêu cầu",
        ),
        sa.Column(
            "expiry_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="Thời điểm hết hạn token",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("password_reset_token_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("password_reset_token_pkey")),
    )
    op.create_index(
        op.f("ix_password_reset_token_token"),
        "password_reset_token",
        ["token"],
        unique=False,
    )
    # ### end Alembic commands ###
