"""refactor(users): add avatar public id

Revision ID: 2d856f81d36f
Revises: f2e83a758bf3
Create Date: 2026-09-29 15:48:56.003238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d856f81d36f'
down_revision: Union[str, Sequence[str], None] = 'f2e83a758bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_public_id', sa.String(length=255), nullable=True, comment='Public ID của avatar trên Cloudinary'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_public_id')
    # ### end Alembic commands ###
