"""create orders order_details order_logs and shipper tables

Revision ID: 6c7e0b8ba4b2
Revises: 8215f0ba4657
Create Date: 2026-09-23 17:09:09.090091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7e0b8ba4b2'
down_revision: Union[str, Sequence[str], None] = '8215f0ba4657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipper',
    sa.Column('shipper_id', sa.Integer(), autoincrement=True, nullable=False, comment='Mã định danh shipper'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Tên shipper / Đơn vị vận chuyển'),
    sa.Column('phone', sa.String(length=10), nullable=False, comment='Số điện thoại liên hệ'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Trạng thái hoạt động (ACTIVE, INACTIVE)'),
    sa.PrimaryKeyConstraint('shipper_id')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=30), nullable=False, comment='Mã định danh đơn hàng'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Mã người mua hàng'),
    sa.Column('order_date', sa.DateTime(), nullable=False, comment='Thời điểm đặt đơn'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Trạng thái đơn hàng (PENDING, PROCESSING, SHIPPED, COMPLETED, CANCELLED)'),
    sa.Column('total', sa.Numeric(precision=38, scale=2), nullable=False, comment='Tổng giá trị đơn hàng'),
    sa.Column('shipping_address', sa.String(length=255), nullable=False, comment='Địa chỉ nhận hàng'),
    sa.Column('receiver_name', sa.String(length=255), nullable=False, comment='Tên người nhận hàng'),
    sa.Column('shipping_phone', sa.String(length=255), nullable=False, comment='Số điện thoại nhận hàng'),
    sa.Column('payment_method', sa.String(length=255), nullable=True, comment='Hình thức thanh toán (COD, VNPAY, MOMO, CREDIT_CARD)'),
    sa.Column('payment_status', sa.String(length=50), nullable=False, comment='Trạng thái thanh toán (PENDING, PAID, FAILED, REFUNDED)'),
    sa.Column('payment_date', sa.DateTime(), nullable=True, comment='Thời điểm thanh toán thành công'),
    sa.Column('delivery_date', sa.DateTime(), nullable=True, comment='Ngày giao hàng thực tế/dự kiến'),
    sa.Column('return_period_day', sa.Integer(), nullable=False, comment='Số ngày cho phép đổi trả'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Thời điểm cập nhật đơn hàng'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_details',
    sa.Column('order_detail_id', sa.Integer(), autoincrement=True, nullable=False, comment='Mã định danh chi tiết đơn'),
    sa.Column('order_id', sa.String(length=30), nullable=False, comment='Đơn hàng liên kết'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Sản phẩm được mua'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Số lượng mua'),
    sa.Column('price', sa.Numeric(precision=38, scale=2), nullable=False, comment='Giá bán của sản phẩm tại thời điểm đặt hàng'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_detail_id')
    )
    op.create_index(op.f('ix_order_details_order_id'), 'order_details', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_details_product_id'), 'order_details', ['product_id'], unique=False)
    op.create_table('order_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Mã định danh bản ghi log'),
    sa.Column('order_id', sa.String(length=30), nullable=False, comment='Đơn hàng được theo dõi'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Trạng thái đơn tại thời điểm ghi log'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Mô tả chi tiết hành động / diễn biến'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='Người thực hiện thao tác'),
    sa.Column('log_date', sa.DateTime(), nullable=False, comment='Thời điểm ghi nhận sự kiện'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Thời điểm cập nhật log'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_logs_order_id'), 'order_logs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_logs_order_id'), table_name='order_logs')
    op.drop_table('order_logs')
    op.drop_index(op.f('ix_order_details_product_id'), table_name='order_details')
    op.drop_index(op.f('ix_order_details_order_id'), table_name='order_details')
    op.drop_table('order_details')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('shipper')
    # ### end Alembic commands ###
