"""create products, categories table (full vers.)

Revision ID: 6cb8d3a3446a
Revises: 37082be2f44b
Create Date: 2026-09-18 11:29:00.699296

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cb8d3a3446a"
down_revision: str | Sequence[str] | None = "37082be2f44b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("category_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category_name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["categories.category_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("category_id"),
        sa.UniqueConstraint("category_name"),
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.add_column(
        "products",
        sa.Column("product_id", sa.Integer(), autoincrement=True, nullable=False),
    )
    # XÓA CỘT 'id' CŨ TRƯỚC (để gỡ bỏ Primary Key cũ của bảng products)
    op.drop_column("products", "id")
    op.drop_column("products", "name")

    # ĐẶT product_id LÀM PRIMARY KEY MỚI
    op.create_primary_key("pk_products", "products", ["product_id"])
    op.add_column(
        "products", sa.Column("product_name", sa.String(length=255), nullable=False)
    )
    op.add_column("products", sa.Column("quantity", sa.Integer(), nullable=False))
    op.add_column("products", sa.Column("sold", sa.Integer(), nullable=False))
    op.add_column(
        "products", sa.Column("discount_percent", sa.Integer(), nullable=True)
    )
    op.add_column(
        "products",
        sa.Column("sale_price", sa.Numeric(precision=38, scale=2), nullable=True),
    )
    op.add_column(
        "products",
        sa.Column("rating", sa.Numeric(precision=38, scale=2), nullable=True),
    )
    op.add_column("products", sa.Column("brand", sa.String(length=255), nullable=True))
    op.add_column("products", sa.Column("origin", sa.String(length=255), nullable=True))
    op.add_column(
        "products", sa.Column("image_src", sa.String(length=255), nullable=True)
    )
    op.add_column("products", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("products", sa.Column("category_id", sa.Integer(), nullable=True))
    op.alter_column(
        "products",
        "price",
        existing_type=sa.NUMERIC(precision=12, scale=2),
        type_=sa.Numeric(precision=38, scale=2),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None,
        "products",
        "categories",
        ["category_id"],
        ["category_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.add_column(
        "products",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "products", type_="foreignkey")
    op.alter_column(
        "products",
        "price",
        existing_type=sa.Numeric(precision=38, scale=2),
        type_=sa.NUMERIC(precision=12, scale=2),
        existing_nullable=False,
    )
    op.drop_column("products", "category_id")
    op.drop_column("products", "description")
    op.drop_column("products", "image_src")
    op.drop_column("products", "origin")
    op.drop_column("products", "brand")
    op.drop_column("products", "rating")
    op.drop_column("products", "sale_price")
    op.drop_column("products", "discount_percent")
    op.drop_column("products", "sold")
    op.drop_column("products", "quantity")
    op.drop_column("products", "product_name")
    op.drop_column("products", "product_id")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
