"""create carts and cart_items tables

Revision ID: 8215f0ba4657
Revises: f2ccaf33440d
Create Date: 2026-09-23 17:03:07.215871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8215f0ba4657'
down_revision: Union[str, Sequence[str], None] = 'f2ccaf33440d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False, comment='Mã định danh giỏ hàng'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Mã người dùng sở hữu giỏ hàng'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.Integer(), autoincrement=True, nullable=False, comment='Mã định danh chi tiết giỏ'),
    sa.Column('cart_id', sa.Integer(), nullable=False, comment='Mã giỏ hàng'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Mã sản phẩm'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Số lượng sản phẩm trong giỏ'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.cart_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_table('carts')
    # ### end Alembic commands ###
