"""add administrative tables

Revision ID: c78373278ca0
Revises: ca4e85213310
Create Date: 2026-09-29 13:21:53.510264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78373278ca0'
down_revision: Union[str, Sequence[str], None] = 'ca4e85213310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('code_name_en', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrative_regions_id'), 'administrative_regions', ['id'], unique=False)
    op.create_table('administrative_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('short_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('code_name_en', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrative_units_id'), 'administrative_units', ['id'], unique=False)
    op.create_table('vn_provinces_metadata',
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('latest_decree', sa.String(length=100), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('dataset_version')
    )
    op.create_table('provinces',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('postal_code_prefix', sa.String(length=255), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('wards',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('full_name_en', sa.String(length=255), nullable=True),
    sa.Column('code_name', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('province_code', sa.String(length=20), nullable=True),
    sa.Column('administrative_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrative_unit_id'], ['administrative_units.id'], ),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wards')
    op.drop_table('provinces')
    op.drop_table('vn_provinces_metadata')
    op.drop_index(op.f('ix_administrative_units_id'), table_name='administrative_units')
    op.drop_table('administrative_units')
    op.drop_index(op.f('ix_administrative_regions_id'), table_name='administrative_regions')
    op.drop_table('administrative_regions')
    # ### end Alembic commands ###
