"""add code to roles table

Revision ID: ca4e85213310
Revises: 2bf29a9be4ea
Create Date: 2026-09-29 08:46:11.790449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4e85213310'
down_revision: Union[str, Sequence[str], None] = '2bf29a9be4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('code', sa.String(length=50), nullable=False, comment='Mã vai trò duy nhất (ADMIN, USER, STAFF...)'))
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Tên hiển thị của vai trò (Quản trị viên, Khách hàng...)',
               existing_comment='Tên vai trò (ROLE_ADMIN, ROLE_USER)',
               existing_nullable=False)
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=255),
               comment='Nguồn đăng nhập (EMAIL, GOOGLE, GITHUB...)',
               existing_comment='Nhà cung cấp xác thực',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider',
               existing_type=sa.VARCHAR(length=255),
               comment='Nhà cung cấp xác thực',
               existing_comment='Nguồn đăng nhập (EMAIL, GOOGLE, GITHUB...)',
               existing_nullable=True)
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Tên vai trò (ROLE_ADMIN, ROLE_USER)',
               existing_comment='Tên hiển thị của vai trò (Quản trị viên, Khách hàng...)',
               existing_nullable=False)
    op.drop_column('roles', 'code')
    # ### end Alembic commands ###
