"""create roles users shipping addresses and auth tokens tables

Revision ID: f2ccaf33440d
Revises: 6cb8d3a3446a
Create Date: 2026-09-23 16:51:10.459158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ccaf33440d'
down_revision: Union[str, Sequence[str], None] = '6cb8d3a3446a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Mã định danh vai trò'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Tên vai trò (ROLE_ADMIN, ROLE_USER)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='UUID định danh duy nhất của người dùng'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Họ và tên người dùng'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Tên đăng nhập duy nhất'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Mật khẩu đã được mã hóa (băm)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Địa chỉ email duy nhất'),
    sa.Column('phone', sa.String(length=255), nullable=True, comment='Số điện thoại duy nhất'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='Địa chỉ liên hệ chính'),
    sa.Column('is_blocked', sa.Boolean(), nullable=False, comment='Trạng thái khóa (False: Hoạt động, True: Khóa)'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='URL ảnh đại diện trên Cloudinary'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='Ngày sinh'),
    sa.Column('provider', sa.String(length=255), nullable=True, comment='Nhà cung cấp đăng nhập (LOCAL, GOOGLE...)'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Mã vai trò (Mặc định 2: USER)'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='Thời điểm đăng nhập gần nhất'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Thời điểm tạo tài khoản'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Thời điểm cập nhật tài khoản gần nhất'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Mã định danh bản ghi'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Chuỗi token đặt lại mật khẩu'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Mã người dùng yêu cầu'),
    sa.Column('expiry_date', sa.DateTime(), nullable=False, comment='Thời điểm hết hạn token'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_token'), 'password_reset_token', ['token'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Mã định danh token'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Chuỗi Refresh Token duy nhất'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Mã người dùng sở hữu token'),
    sa.Column('expiry_date', sa.DateTime(), nullable=False, comment='Thời điểm hết hạn của refresh token'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_refresh_token_token'), 'refresh_token', ['token'], unique=True)
    op.create_table('shipping_addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Mã định danh địa chỉ'),
    sa.Column('receiver_name', sa.String(length=255), nullable=False, comment='Họ tên người nhận hàng'),
    sa.Column('phone', sa.String(length=255), nullable=False, comment='Số điện thoại người nhận hàng'),
    sa.Column('address', sa.String(length=255), nullable=False, comment='Địa chỉ nhận hàng chi tiết'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Mã người dùng sở hữu địa chỉ'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_addresses_user_id'), 'shipping_addresses', ['user_id'], unique=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['category_id'], ondelete='SET NULL')
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_shipping_addresses_user_id'), table_name='shipping_addresses')
    op.drop_table('shipping_addresses')
    op.drop_index(op.f('ix_refresh_token_token'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_password_reset_token_token'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
