"""refactor(users): remove address field

Revision ID: f2e83a758bf3
Revises: 25e5292b1b53
Create Date: 2026-09-29 15:01:49.268325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e83a758bf3'
down_revision: Union[str, Sequence[str], None] = '25e5292b1b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Địa chỉ liên hệ chính'))
    # ### end Alembic commands ###
